# Generated by Django 3.2.23 on 2024-04-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ramcipak', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
